using Microsoft.Data.SqlClient;

namespace Recon.Data;

/// <summary>
/// Thin helpers over <see cref="SqlCommand"/>.
///
/// <para>
/// Dapper or EF would do this, and neither is here on purpose. The engine's
/// queries are either generated by
/// <c>Recon.Engine.Sql.SqlQueryBuilder</c> — which must be the only thing that
/// emits SQL — or short fixed statements like these. An ORM would add a second
/// SQL generator to a codebase whose central safety claim is that there is
/// exactly one.
/// </para>
/// </summary>
public static class Db
{
    public static SqlCommand Command(SqlConnection connection, string sql, int timeoutSeconds = 600)
    {
        ArgumentNullException.ThrowIfNull(connection);

        var command = connection.CreateCommand();
        command.CommandText = sql;
        command.CommandTimeout = timeoutSeconds;
        return command;
    }

    public static SqlCommand With(this SqlCommand command, string name, object? value)
    {
        ArgumentNullException.ThrowIfNull(command);
        command.Parameters.AddWithValue(name, value ?? DBNull.Value);
        return command;
    }

    public static async Task<T?> ScalarAsync<T>(
        SqlConnection connection,
        string sql,
        Action<SqlCommand>? bind = null,
        CancellationToken cancellationToken = default)
    {
        using var command = Command(connection, sql);
        bind?.Invoke(command);

        var result = await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
        return result is null or DBNull ? default : (T)result;
    }

    public static async Task<int> ExecuteAsync(
        SqlConnection connection,
        string sql,
        Action<SqlCommand>? bind = null,
        CancellationToken cancellationToken = default)
    {
        using var command = Command(connection, sql);
        bind?.Invoke(command);
        return await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    public static async Task<List<T>> QueryAsync<T>(
        SqlConnection connection,
        string sql,
        Func<SqlDataReader, T> map,
        Action<SqlCommand>? bind = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(map);

        using var command = Command(connection, sql);
        bind?.Invoke(command);

        var results = new List<T>();
        using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);

        while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            results.Add(map(reader));
        }

        return results;
    }

    public static string? GetNullableString(this SqlDataReader reader, string name)
    {
        var i = reader.GetOrdinal(name);
        return reader.IsDBNull(i) ? null : reader.GetString(i);
    }

    public static int? GetNullableInt32(this SqlDataReader reader, string name)
    {
        var i = reader.GetOrdinal(name);
        return reader.IsDBNull(i) ? null : reader.GetInt32(i);
    }

    public static long? GetNullableInt64(this SqlDataReader reader, string name)
    {
        var i = reader.GetOrdinal(name);
        return reader.IsDBNull(i) ? null : reader.GetInt64(i);
    }

    public static T ParseEnum<T>(string value) where T : struct, Enum =>
        // Case-SENSITIVE on purpose: the database collates its enum whitelists
        // case-sensitively (review finding X1), so a value that differs only in
        // case has bypassed a constraint and should surface, not be accepted.
        Enum.TryParse<T>(value, ignoreCase: false, out var parsed)
            ? parsed
            : throw new InvalidOperationException(
                $"'{value}' is not a valid {typeof(T).Name}. The database and the code disagree " +
                "about this vocabulary, which usually means a CHECK constraint was bypassed.");
}
