<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Recon.Data</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Recon.Domain/Recon.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>
</Project>
